import React, { useState, useEffect } from 'react';
import { MyPage } from '../../components/common/types';

// Swell
import { swellClient } from '@/swell/connection';
import { getAllProducts } from '@/swell/queries';

// Components
import Product from './components/product';
import ProductControl from './components/productControl';

import { productsInterface } from '@/@types/product';
import { SyncLoader } from 'react-spinners';

import { SparklesIcon } from '@heroicons/react/24/outline';

const HomePage: MyPage = () => {
    const [products, setProducts] = useState<productsInterface>();
    const getProducts = () => {
        try {
            swellClient.request<productsInterface>(getAllProducts).then<void>((value) => {
                setProducts(value);
            });
        } catch (err) {
            console.error(err);
        }
    };

    useEffect(() => {
        getProducts();
    }, []);

    return (
        <>
            <link rel='icon' href='/favicon.ico' />
            <div className='container mx-auto'>
                <div
                    className='relative bg-cover bg-center bg-no-repeat h-96 rounded-lg'
                    style={{ backgroundImage: 'url("/hero.jpg")' }}
                >
                    <div className='absolute start-28 top-32'>
                        <h1 className='text-3xl w-64 text-indigo-500'>
                            Everything you need in one place.
                        </h1>
                        <button className='flex rounded-full bg-indigo-500 px-3 py-2 mt-4'>
                            <SparklesIcon className='h-6 w-6 text-white mr-1' />
                            <h1 className='text-xl text-white'>Get Started</h1>
                        </button>
                    </div>
                </div>

                <ProductControl />

                <h2 className='my-3 text-lg'>Featured Products</h2>
                {products?.products.results ? (
                    <div className='grid md:grid-cols-5 sm:grid-cols-2 gap-4 min-h-screen'>
                        {products?.products.results.map((product) => (
                            <Product product={product} />
                        ))}
                    </div>
                ) : (
                    <div className='flex place-content-center'>
                        <SyncLoader color='#94a3b8' />
                    </div>
                )}
            </div>
        </>
    );
};
export default HomePage;
HomePage.Layout = 'Main';
// HomePage.Layout = "OtherLayout"; -> error Type '"OtherLayout"' is not assignable to type '"Main" | "Admin" | undefined'.

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>src/pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
